# Generated by Django 5.0 on 2023-12-14 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ دسته بندی')),
                ('image', models.ImageField(upload_to='categories/images/', verbose_name='تصویر دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام برچسب')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ برچسب')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
            },
        ),
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='تایتل بیت')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ(url)')),
                ('bpm', models.BigIntegerField()),
                ('keys', models.CharField(max_length=20)),
                ('publish', models.DateField(blank=True, null=True, verbose_name='زمان انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='bits/images/image/', verbose_name='تصویر بیت')),
                ('mp3_free', models.FileField(upload_to='bits/files/mp3/free/', verbose_name='mp3 رایگان')),
                ('mp3_no_tag_in', models.FileField(upload_to='bits/files/mp3/no_tag/', verbose_name='pm3 پولی')),
                ('wav', models.FileField(upload_to='bits/files/wav/', verbose_name='فایل wav')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('َAC', 'Accepted'), ('RJ', 'Rejected')], default='DF', max_length=3)),
                ('plays', models.IntegerField(default=0, verbose_name='تعداد پلی')),
                ('likes', models.IntegerField(default=0, verbose_name='تعداد لایک')),
                ('dislikes', models.IntegerField(default=0, verbose_name='تعداد dislike ها')),
                ('comments', models.IntegerField(default=0, verbose_name='تعداد کامنت ها')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bit_producer', to=settings.AUTH_USER_MODEL, verbose_name='پرودوسر')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beats.category', verbose_name='دسته بندی')),
                ('tags', models.ManyToManyField(blank=True, to='beats.tag', verbose_name='برچسب ها')),
            ],
            options={
                'verbose_name': 'بیت',
                'verbose_name_plural': 'بیت ها',
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='کامنت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آخرین آپدیت')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان کامنت')),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bit_comments', to='beats.beat', verbose_name='کامنت های بیت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL, verbose_name='کامنت کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
                'ordering': ['created'],
            },
        ),
    ]
