# Generated by Django 5.0 on 2023-12-16 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='published_status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PU', 'Published')], default='DF', max_length=2),
        ),
        migrations.AlterField(
            model_name='beat',
            name='image',
            field=models.ImageField(upload_to='Beats/images/image/', verbose_name='تصویر بیت'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='mp3_free',
            field=models.FileField(upload_to='Beats/files/mp3/free/', verbose_name='mp3 رایگان'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='mp3_no_tag_in',
            field=models.FileField(upload_to='Beats/files/mp3/no_tag/', verbose_name='pm3 پولی'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer', to=settings.AUTH_USER_MODEL, verbose_name='پرودوسر'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='status',
            field=models.CharField(choices=[('َAC', 'Accepted'), ('RJ', 'Rejected'), ('CH', 'Checking')], default='CH', max_length=3),
        ),
        migrations.AlterField(
            model_name='beat',
            name='wav',
            field=models.FileField(upload_to='Beats/files/wav/', verbose_name='فایل wav'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='beat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Beat_comments', to='beats.beat', verbose_name='کامنت های بیت'),
        ),
    ]
