# Generated by Django 5.0 on 2023-12-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0003_basicbeatlicence_permiumbeatlicence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='bpm',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Beats/images/image/', verbose_name='تصویر بیت'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='keys',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='beat',
            name='mp3_free',
            field=models.FileField(blank=True, null=True, upload_to='Beats/files/mp3/free/', verbose_name='mp3 رایگان'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='mp3_no_tag_in',
            field=models.FileField(blank=True, null=True, upload_to='Beats/files/mp3/no_tag/', verbose_name='pm3 پولی'),
        ),
        migrations.AlterField(
            model_name='beat',
            name='wav',
            field=models.FileField(blank=True, null=True, upload_to='Beats/files/wav/', verbose_name='فایل wav'),
        ),
    ]
