# Generated by Django 5.0 on 2023-12-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0004_alter_beat_bpm_alter_beat_image_alter_beat_keys_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='published_status',
        ),
        migrations.AddField(
            model_name='beat',
            name='mai_status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PU', 'Public'), ('PR', 'Private')], default='DF', max_length=2),
        ),
    ]
