# Generated by Django 5.0 on 2023-12-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0005_remove_beat_published_status_beat_mai_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='mai_status',
        ),
        migrations.AddField(
            model_name='beat',
            name='main_status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PU', 'Public'), ('PR', 'Private')], default='DF', max_length=2),
        ),
    ]
