# Generated by Django 5.0 on 2023-12-22 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0006_remove_beat_mai_status_beat_main_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeatDisLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_disliked', models.BooleanField(default=False)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beat_dislike', to='beats.beat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_beat_dislike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BeatLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=False)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beat_likes', to='beats.beat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_beat_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
