# Generated by Django 5.0 on 2023-12-24 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0007_beatdislike_beatlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basicbeatlicence',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_basic_licence_owner', to=settings.AUTH_USER_MODEL, verbose_name='خریدار'),
        ),
        migrations.AddField(
            model_name='permiumbeatlicence',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_permium_licence_owner', to=settings.AUTH_USER_MODEL, verbose_name='خریدار'),
        ),
        migrations.AlterField(
            model_name='basicbeatlicence',
            name='price',
            field=models.BigIntegerField(default=300000, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='permiumbeatlicence',
            name='price',
            field=models.BigIntegerField(default=500000, verbose_name='قیمت'),
        ),
    ]
