# Generated by Django 5.0 on 2023-12-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0008_basicbeatlicence_user_permiumbeatlicence_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='basic_licence_status',
            field=models.BooleanField(default=True, verbose_name='وضعیت اشتراک بیسیک'),
        ),
        migrations.AddField(
            model_name='beat',
            name='permium_licence_status',
            field=models.BooleanField(default=True, verbose_name='وضعیت اشتراک پرمیوم'),
        ),
    ]
