# Generated by Django 5.0 on 2023-12-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0009_beat_basic_licence_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='پابلیک شده'),
        ),
    ]
