# Generated by Django 5.0 on 2023-12-13 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلقن')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('username', models.CharField(max_length=20, verbose_name='نام کربری')),
                ('password', models.CharField(max_length=16)),
                ('password2', models.CharField(max_length=16)),
                ('token', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=6)),
                ('type', models.CharField(choices=[('SIU', 'Simple_user'), ('SIN', 'Singer'), ('PRD', 'Producer'), ('MUC', 'Musician'), ('SPO', 'Supporter')], default='SIU', max_length=3)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('type', models.CharField(choices=[('SIU', 'Simple_user'), ('SIN', 'Singer'), ('PRD', 'Producer'), ('MUC', 'Musician'), ('SPO', 'Supporter')], max_length=3)),
                ('status', models.CharField(choices=[('OFL', 'Official'), ('UFL', 'Un_Official')], default='UFL', max_length=3, verbose_name='وضعیت کاربر')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('username', models.CharField(max_length=40, unique=True, verbose_name='نام کاربر')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='اسلاگ پروفایل')),
                ('joined', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر ها',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='UserFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qountity', models.IntegerField(default=0)),
                ('follower_user', models.ManyToManyField(blank=True, related_name='follower_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_followers', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qountity', models.IntegerField(default=0)),
                ('following_user', models.ManyToManyField(blank=True, related_name='following_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_followings', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistic_name', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='نام هنری')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='بیوگرافی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='تصویر پروفایل')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام کامل کاربر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر ساده',
                'verbose_name_plural': 'پروفایل کاربران ساده',
            },
        ),
        migrations.CreateModel(
            name='UserSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('facebook', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('youtube', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('sound_cloud', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('tik_tok', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_social_media', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
