# Generated by Django 4.0.1 on 2023-12-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('type', models.CharField(choices=[('SIU', 'Simple_user'), ('SIN', 'Singer'), ('PRD', 'Producer'), ('MUC', 'Musician'), ('SPO', 'Supporter')], max_length=3)),
                ('status', models.CharField(choices=[('OFL', 'Official'), ('UFL', 'Un_Official')], default='UFL', max_length=3, verbose_name='وضعیت کاربر')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('username', models.CharField(max_length=40, unique=True, verbose_name='نام کاربر')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='اسلاگ پروفایل')),
                ('joined', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر ها',
                'ordering': ['type'],
            },
        ),
    ]
