# Generated by Django 5.0 on 2023-12-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollower',
            options={'verbose_name': 'فالور', 'verbose_name_plural': 'فالور ها'},
        ),
        migrations.AlterModelOptions(
            name='userfollowing',
            options={'verbose_name': 'دنبال کننده', 'verbose_name_plural': 'دنبال کنندگان'},
        ),
        migrations.AlterField(
            model_name='otp',
            name='type',
            field=models.CharField(choices=[('SIM', 'Simple_user'), ('SIN', 'Singer'), ('PRD', 'Producer'), ('MUC', 'Musician'), ('SPO', 'Supporter')], default='SIM', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('SIM', 'Simple_user'), ('SIN', 'Singer'), ('PRD', 'Producer'), ('MUC', 'Musician'), ('SPO', 'Supporter')], max_length=3),
        ),
    ]
