# Generated by Django 4.0.1 on 2023-12-11 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'موزیسین',
                'verbose_name_plural': 'موزیسین ها',
                'ordering': ['status'],
            },
            bases=('account.user',),
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پرودوسر',
                'verbose_name_plural': 'پرودوسر ها',
                'ordering': ['status'],
            },
            bases=('account.user',),
        ),
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کاربر ساده',
                'verbose_name_plural': 'کاربران ساده',
            },
            bases=('account.user',),
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'خواننده',
                'verbose_name_plural': 'خوانندگان',
                'ordering': ['status'],
            },
            bases=('account.user',),
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('supporter_id', models.CharField(max_length=20, unique=True, verbose_name='آیدی پشتیبان')),
                ('supporter_password', models.CharField(max_length=16, verbose_name='رمز عبور پشتیبان')),
            ],
            options={
                'verbose_name': 'پشتیبان',
                'verbose_name_plural': 'پشتیبان ها',
                'ordering': ['supporter_id'],
            },
            bases=('account.user',),
        ),
        migrations.CreateModel(
            name='SingerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistic_name', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='نام هنری')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='بیوگرافی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='singer/image/profile/', verbose_name='تصویر پروفایل')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام کامل کاربر')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singer_user_profile', to='account.singer', verbose_name='پروفایل خواننده')),
            ],
            options={
                'verbose_name': 'پروفایل خواننده',
                'verbose_name_plural': 'پروفایل خوانندگان',
            },
        ),
        migrations.CreateModel(
            name='SimpleUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='بیوگرافی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='تصویر پروفایل')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام کامل کاربر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_user_profile', to='account.simpleuser', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر ساده',
                'verbose_name_plural': 'پروفایل کاربران ساده',
            },
        ),
        migrations.CreateModel(
            name='ProducerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistic_name', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='نام هنری')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='بیوگرافی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='singer/image/profile/', verbose_name='تصویر پروفایل')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام کامل کاربر')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_user_profile', to='account.producer', verbose_name='پرودوسر')),
            ],
            options={
                'verbose_name': 'پروفایل پرودوسر',
                'verbose_name_plural': 'پروفایل پرودوسرها',
            },
        ),
        migrations.CreateModel(
            name='MusicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistic_name', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='نام هنری')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='بیوگرافی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='singer/image/profile/', verbose_name='تصویر پروفایل')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام کامل کاربر')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musician_user_profile', to='account.musician', verbose_name='موزیسین')),
            ],
            options={
                'verbose_name': 'پروفایل موزیسین',
                'verbose_name_plural': 'پروفایل موزیسین ها',
            },
        ),
    ]
