# Generated by Django 5.0 on 2023-12-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_userbankaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
    ]
